### ISSUE TITLE
apt Update check 2.9.0 not working in check_mk 1.6.0p6

### ISSUE THREAD

**Issue by Meridiana** [lgbff/lgb_check_mk_plugins#15]
After upgrading from 1.5.0p11.cee to 1.6.0p6.cee the plugin gives errors:

The "extension packages" page shows: 
Loading "/omd/sites/nagios/local/share/check_mk/web/plugins/wato/apt_check_pameters.py" failed

And on the "services" page of a host:
Invalid check parameter: The type must be a dictionary, but it is a NoneType
Variable: checkgroup_parameters:apt
Parameters:

None

**Comment by marvinwankersteen** [comment]
Same problem with the current version `check-mk-raw-1.6.0p15`.
This error is logged each time the WebGUI is loaded.
```
$ cat ~/var/log/web.log
2020-08-10 09:46:41,818 [40] [cmk.web 18493] Failed to load plugin /omd/sites/<site>/local/share/check_mk/web/plugins/wato/apt_check_pameters.py: 
Traceback (most recent call last):
  File "/omd/sites/<site>/lib/python/cmk/gui/utils.py", line 173, in load_web_plugins
    execfile(file_path, globalvars)
  File "/omd/sites/<site>/local/share/check_mk/web/plugins/wato/apt_check_pameters.py", line 15, in <module>
    None, None
  File "/omd/sites/<site>/lib/python/cmk/gui/plugins/wato/utils/__init__.py", line 724, in register_check_parameters
    raise NotImplementedError()
NotImplementedError
```

**Comment by schoekek** [comment]
pls use the latest version from check_mk exchange.
